/**
 * Mock 数据 — 首页和详情页开发使用
 * 基于长沙 IFS + 五一广场真实商家
 */
import type { Deal } from '../models/deal'
import type { Merchant } from '../models/merchant'

export const mockMerchants: Merchant[] = [
    {
        id: 'm001',
        name: '费大厨辣椒炒肉',
        category: 'food',
        address: '长沙 IFS 国金中心 L7',
        lat: 28.19720,
        lng: 112.97690,
        district: '芙蓉区',
        mall: 'IFS 国金中心',
        avgSpend: 85,
        popularityScore: 92,
        rating: 4.6,
        source: 'manual',
        updatedAt: '2026-02-25',
        createdAt: '2026-02-20',
    },
    {
        id: 'm002',
        name: '茶颜悦色·五一广场旗舰店',
        category: 'tea',
        address: '五一广场地铁站2号口',
        lat: 28.19520,
        lng: 112.97380,
        district: '天心区',
        mall: null,
        avgSpend: 18,
        popularityScore: 98,
        rating: 4.8,
        source: 'manual',
        updatedAt: '2026-02-25',
        createdAt: '2026-02-20',
    },
    {
        id: 'm003',
        name: '黑色经典臭豆腐',
        category: 'food',
        address: '太平街口',
        lat: 28.19310,
        lng: 112.97190,
        district: '天心区',
        mall: null,
        avgSpend: 25,
        popularityScore: 95,
        rating: 4.5,
        source: 'manual',
        updatedAt: '2026-02-25',
        createdAt: '2026-02-20',
    },
    {
        id: 'm004',
        name: '虾小龙·长沙小龙虾',
        category: 'food',
        address: 'IFS 国金中心 L6',
        lat: 28.19710,
        lng: 112.97680,
        district: '芙蓉区',
        mall: 'IFS 国金中心',
        avgSpend: 120,
        popularityScore: 88,
        rating: 4.4,
        source: 'manual',
        updatedAt: '2026-02-25',
        createdAt: '2026-02-20',
    },
    {
        id: 'm005',
        name: '文和友老长沙龙虾馆',
        category: 'food',
        address: '海信广场ΜΑLL',
        lat: 28.19640,
        lng: 112.97880,
        district: '芙蓉区',
        mall: '海信广场',
        avgSpend: 150,
        popularityScore: 90,
        rating: 4.3,
        source: 'manual',
        updatedAt: '2026-02-25',
        createdAt: '2026-02-20',
    },
    {
        id: 'm006',
        name: '墨茉点心局·IFS 店',
        category: 'dessert',
        address: 'IFS 国金中心 B1',
        lat: 28.19730,
        lng: 112.97700,
        district: '芙蓉区',
        mall: 'IFS 国金中心',
        avgSpend: 35,
        popularityScore: 87,
        rating: 4.5,
        source: 'manual',
        updatedAt: '2026-02-25',
        createdAt: '2026-02-20',
    },
]

export const mockDeals: (Deal & { merchantName?: string })[] = [
    {
        id: 'd001',
        merchantId: 'm001',
        merchantName: '费大厨辣椒炒肉',
        title: '双人套餐·招牌辣椒炒肉+剁椒鱼头',
        platform: '美团',
        scene: 'dine_in',
        discountType: 'GROUP_BUY',
        discountValue: 0,
        thresholdAmount: null,
        maxDiscount: null,
        price: 128,
        originalPrice: 186,
        stackable: false,
        stackGroup: null,
        stackExclusiveType: null,
        appliesStage: 'BASE',
        cardRequired: null,
        membershipRequired: null,
        conditions: null,
        validFrom: '2026-02-01',
        validTo: '2026-04-30',
        affiliateUrl: 'https://meitu.an/example',
        isActive: true,
        recurrenceType: 'NONE',
        recurrenceRule: null,
        notifyOnNew: true,
        estimatedMinSave: null,
        estimatedMaxSave: null,
        voucherClaimUrl: null,
        updatedAt: '2026-02-24',
        createdAt: '2026-02-20',
    },
    {
        id: 'd002',
        merchantId: 'm001',
        merchantName: '费大厨辣椒炒肉',
        title: '抖音团购·3人聚餐套餐',
        platform: '抖音',
        scene: 'dine_in',
        discountType: 'GROUP_BUY',
        discountValue: 0,
        thresholdAmount: null,
        maxDiscount: null,
        price: 198,
        originalPrice: 280,
        stackable: false,
        stackGroup: null,
        stackExclusiveType: null,
        appliesStage: 'BASE',
        cardRequired: null,
        membershipRequired: null,
        conditions: null,
        validFrom: '2026-02-01',
        validTo: '2026-04-30',
        affiliateUrl: 'https://douyin.com/example',
        isActive: true,
        recurrenceType: 'NONE',
        recurrenceRule: null,
        notifyOnNew: true,
        estimatedMinSave: null,
        estimatedMaxSave: null,
        voucherClaimUrl: null,
        updatedAt: '2026-02-24',
        createdAt: '2026-02-20',
    },
    {
        id: 'd003',
        merchantId: 'm001',
        merchantName: '费大厨辣椒炒肉',
        title: '招行信用卡满100减30',
        platform: '招商银行',
        scene: 'dine_in',
        discountType: 'FULL_REDUCE',
        discountValue: 30,
        thresholdAmount: 100,
        maxDiscount: 30,
        price: null,
        originalPrice: null,
        stackable: false,
        stackGroup: 'bank_dine',
        stackExclusiveType: 'HARD',
        appliesStage: 'BASE',
        cardRequired: '招行信用卡',
        membershipRequired: null,
        conditions: '每周四限量',
        validFrom: '2026-01-01',
        validTo: '2026-06-30',
        affiliateUrl: null,
        isActive: true,
        recurrenceType: 'WEEKLY',
        recurrenceRule: 'thu',
        notifyOnNew: false,
        estimatedMinSave: null,
        estimatedMaxSave: null,
        voucherClaimUrl: null,
        updatedAt: '2026-02-24',
        createdAt: '2026-02-20',
    },
    {
        id: 'd004',
        merchantId: 'm001',
        merchantName: '费大厨辣椒炒肉',
        title: '建行龙支付满150减40',
        platform: '建设银行',
        scene: 'dine_in',
        discountType: 'FULL_REDUCE',
        discountValue: 40,
        thresholdAmount: 150,
        maxDiscount: 40,
        price: null,
        originalPrice: null,
        stackable: false,
        stackGroup: 'bank_dine',
        stackExclusiveType: 'HARD',
        appliesStage: 'BASE',
        cardRequired: '建行信用卡',
        membershipRequired: null,
        conditions: '每周六日',
        validFrom: '2026-01-01',
        validTo: '2026-06-30',
        affiliateUrl: null,
        isActive: true,
        recurrenceType: 'WEEKLY',
        recurrenceRule: 'sat,sun',
        notifyOnNew: false,
        estimatedMinSave: null,
        estimatedMaxSave: null,
        voucherClaimUrl: null,
        updatedAt: '2026-02-24',
        createdAt: '2026-02-20',
    },
    {
        id: 'd005',
        merchantId: 'm002',
        merchantName: '茶颜悦色·五一广场旗舰店',
        title: '幽兰拿铁+声声乌龙双杯套餐',
        platform: '美团',
        scene: 'dine_in',
        discountType: 'GROUP_BUY',
        discountValue: 0,
        thresholdAmount: null,
        maxDiscount: null,
        price: 28,
        originalPrice: 36,
        stackable: false,
        stackGroup: null,
        stackExclusiveType: null,
        appliesStage: 'BASE',
        cardRequired: null,
        membershipRequired: null,
        conditions: null,
        validFrom: '2026-02-01',
        validTo: '2026-05-31',
        affiliateUrl: 'https://meitu.an/example2',
        isActive: true,
        recurrenceType: 'NONE',
        recurrenceRule: null,
        notifyOnNew: true,
        estimatedMinSave: null,
        estimatedMaxSave: null,
        voucherClaimUrl: null,
        updatedAt: '2026-02-24',
        createdAt: '2026-02-20',
    },
    {
        id: 'd006',
        merchantId: 'm003',
        merchantName: '黑色经典臭豆腐',
        title: '经典臭豆腐+糖油粑粑组合',
        platform: '抖音',
        scene: 'dine_in',
        discountType: 'GROUP_BUY',
        discountValue: 0,
        thresholdAmount: null,
        maxDiscount: null,
        price: 19.9,
        originalPrice: 32,
        stackable: false,
        stackGroup: null,
        stackExclusiveType: null,
        appliesStage: 'BASE',
        cardRequired: null,
        membershipRequired: null,
        conditions: null,
        validFrom: '2026-02-01',
        validTo: '2026-04-30',
        affiliateUrl: 'https://douyin.com/example2',
        isActive: true,
        recurrenceType: 'NONE',
        recurrenceRule: null,
        notifyOnNew: true,
        estimatedMinSave: null,
        estimatedMaxSave: null,
        voucherClaimUrl: null,
        updatedAt: '2026-02-24',
        createdAt: '2026-02-20',
    },
    {
        id: 'd007',
        merchantId: 'm005',
        merchantName: '文和友老长沙龙虾馆',
        title: '美团85折券',
        platform: '美团',
        scene: 'dine_in',
        discountType: 'PERCENTAGE',
        discountValue: 0.85,
        thresholdAmount: null,
        maxDiscount: 50,
        price: null,
        originalPrice: null,
        stackable: false,
        stackGroup: null,
        stackExclusiveType: null,
        appliesStage: 'BASE',
        cardRequired: null,
        membershipRequired: null,
        conditions: null,
        validFrom: '2026-02-01',
        validTo: '2026-04-30',
        affiliateUrl: 'https://meitu.an/example3',
        isActive: true,
        recurrenceType: 'NONE',
        recurrenceRule: null,
        notifyOnNew: true,
        estimatedMinSave: null,
        estimatedMaxSave: null,
        voucherClaimUrl: null,
        updatedAt: '2026-02-24',
        createdAt: '2026-02-20',
    },
    {
        id: 'd008',
        merchantId: 'm006',
        merchantName: '墨茉点心局·IFS 店',
        title: '人气爆款3件套',
        platform: '美团',
        scene: 'dine_in',
        discountType: 'GROUP_BUY',
        discountValue: 0,
        thresholdAmount: null,
        maxDiscount: null,
        price: 29.9,
        originalPrice: 42,
        stackable: false,
        stackGroup: null,
        stackExclusiveType: null,
        appliesStage: 'BASE',
        cardRequired: null,
        membershipRequired: null,
        conditions: null,
        validFrom: '2026-02-01',
        validTo: '2026-04-30',
        affiliateUrl: 'https://meitu.an/example4',
        isActive: true,
        recurrenceType: 'NONE',
        recurrenceRule: null,
        notifyOnNew: true,
        estimatedMinSave: null,
        estimatedMaxSave: null,
        voucherClaimUrl: null,
        updatedAt: '2026-02-24',
        createdAt: '2026-02-20',
    },
    // ---- 限时抢购优惠 ----
    {
        id: 'd-flash-1',
        merchantId: 'm002',
        merchantName: '茶颜悦色·五一广场旗舰店',
        title: '🔥 限时秒杀·声声乌龙买一送一',
        platform: '小程序',
        scene: 'dine_in',
        discountType: 'GROUP_BUY',
        discountValue: 0,
        thresholdAmount: null,
        maxDiscount: null,
        price: 12,
        originalPrice: 24,
        stackable: false,
        stackGroup: null,
        stackExclusiveType: null,
        appliesStage: 'BASE',
        cardRequired: null,
        membershipRequired: null,
        conditions: '限量 200 份',
        // 2 小时后开抢
        validFrom: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
        validTo: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
        affiliateUrl: null,
        isActive: true,
        recurrenceType: 'NONE',
        recurrenceRule: null,
        notifyOnNew: true,
        estimatedMinSave: null,
        estimatedMaxSave: null,
        voucherClaimUrl: null,
        updatedAt: '2026-02-28',
        createdAt: '2026-02-28',
    },
    {
        id: 'd-flash-2',
        merchantId: 'm005',
        merchantName: '文和友老长沙龙虾馆',
        title: '⚡ 限时特惠·小龙虾3斤套餐',
        platform: '美团',
        scene: 'dine_in',
        discountType: 'GROUP_BUY',
        discountValue: 0,
        thresholdAmount: null,
        maxDiscount: null,
        price: 99,
        originalPrice: 198,
        stackable: false,
        stackGroup: null,
        stackExclusiveType: null,
        appliesStage: 'BASE',
        cardRequired: null,
        membershipRequired: null,
        conditions: '每日限量 50 份',
        // 已开抢，6 小时后结束
        validFrom: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        validTo: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
        affiliateUrl: 'https://meitu.an/example-flash',
        isActive: true,
        recurrenceType: 'NONE',
        recurrenceRule: null,
        notifyOnNew: true,
        estimatedMinSave: null,
        estimatedMaxSave: null,
        voucherClaimUrl: null,
        updatedAt: '2026-02-28',
        createdAt: '2026-02-28',
    },
]

/** 获取商家下所有优惠 */
export function getMockDealsByMerchant(merchantId: string): typeof mockDeals {
    return mockDeals.filter(d => d.merchantId === merchantId)
}

/** 获取商家信息 */
export function getMockMerchant(merchantId: string): Merchant | undefined {
    return mockMerchants.find(m => m.id === merchantId)
}

/** 获取今日最高可省金额 */
export function getMockMaxSaving(): number {
    let maxSave = 0
    for (const deal of mockDeals) {
        if (deal.discountType === 'GROUP_BUY' && deal.originalPrice && deal.price) {
            const save = deal.originalPrice - deal.price
            if (save > maxSave) maxSave = save
        } else if (deal.discountType === 'FULL_REDUCE') {
            if (deal.discountValue > maxSave) maxSave = deal.discountValue
        }
    }
    return maxSave
}
